@ninjas_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjI1Nzc3NDR9._u03OrZBk-UrU8IKUluu0Augx2IiGlqxEj_KtupX7Ss

@nicks_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NjI1Nzc3Njl9.5g_pvL2VYZ_yBeyT9U69o9LPyaB_UUT-YOwMs1DZBsQ

@wubsaws_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NjI1Nzc4Nzd9.N-Z1zjB91yu-811dhCnGIwFhAmdDRAQ3r57JHHNpQaY

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "wubsaw",
  "email": "wubsaw@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "wubsaw@test.com",
  "password": "password"
}

### Create Post
POST http://localhost:3000/posts
Authorization: Bearer {{ninjas_jwt}}
Content-Type: application/json

{
	"title": "How do you do 90s again",
	"body": "I forgot...",
  "game_id": 1
}

### Update Post
PATCH http://localhost:3000/posts/11
Authorization: Bearer {{nicks_jwt}}
Content-Type: application/json

{
"title": "Anyone down to play besides Ninja???",
"body": "Please don't invite him either...",
"game_id": 1
}

### Delete post
DELETE http://localhost:3000/posts/15.json
Authorization: Bearer {{ninjas_jwt}}
Content-Type: application/json


# ### Delete User (USED TO DELETE FIRST 2 USERS)
# DELETE http://localhost:3000/users/2.json
# Content-Type: application/json

### Show All Games
GET http://localhost:3000/games.json

### Show Specific Game
GET http://localhost:3000/games/1.json

### Show All Posts
GET http://localhost:3000/posts.json
