@ninjas_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjIyMzE0OTh9.iZLIaZTYsz6S1oW0APKRonS89gMWEyDT-NC8U58dZXQ

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "Ninja",
  "email": "ninja@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ninja@test.com",
  "password": "password"
}

### Create Post
POST http://localhost:3000/posts
Authorization: Bearer {{ninjas_jwt}}
Content-Type: application/json

{
	"title": "TEST post",
	"body": "lololol",
  "game_id": 2
}

### Update Post
PATCH http://localhost:3000/posts/7
Authorization: Bearer {{ninjas_jwt}}
Content-Type: application/json

{
"title": "Lucky numba 7",
"body": "did it work?",
"game_id": 4
}

### Delete post
DELETE http://localhost:3000/posts/6.json
Authorization: Bearer {{ninjas_jwt}}
Content-Type: application/json


# ### Delete User (USED TO DELETE FIRST 2 USERS)
# DELETE http://localhost:3000/users/2.json
# Content-Type: application/json

### Show All Games
GET http://localhost:3000/games.json

### Show Specific Game
GET http://localhost:3000/games/1.json

### Show All Posts
GET http://localhost:3000/posts.json
